# Generated by Django 2.2 on 2019-11-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='group',
            field=models.ForeignKey(default='282ed101-f9c6-40d7-9a6d-9eb926d053ba', on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='CustomUsers.UserGroupModel'),
        ),
    ]
