# Generated by Django 2.2 on 2019-11-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='address',
            field=models.TextField(default='TON618', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='area',
            field=models.CharField(max_length=80, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='fb_page_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Page Link'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='image',
            field=models.ImageField(default='users/defaults/user.png', upload_to='users/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Page Link'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='nid_number',
            field=models.CharField(default='0', max_length=40, unique=True, verbose_name='NID Number'),
        ),
        migrations.AlterField(
            model_name='usergroupmodel',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Group Name'),
        ),
    ]
