# Generated by Django 2.2 on 2019-11-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0002_auto_20191103_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='CustomUsers.UserGroupModel'),
        ),
    ]
