# Generated by Django 2.2 on 2019-11-03 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0003_auto_20191103_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
